### ISSUE TITLE
Invalid variable "type" after conversion from HCL

### ISSUE THREAD

**Issue by GitYukari** [MertSenel/Hcl2PS#13]
Hi, this is a great tool and it works beautifully to allow editing of HCL as objects in PowerShell.

However, I'm encountering an issue when validating the generated json with packer.

For example, if this variable is defined in the source HCL:
```
variable "tenant_id" {
  type    = string
  default = "${env("ARM_TENANT_ID")}"
}
```

The Hcl2PS module converts this to:
```
"tenant_id": [
    {
        "default": "${env(\"ARM_TENANT_ID\")}",
        "type": "${string}"
    }
]
```

Then, when running packer validate: `packer validate .\windows.pkr.json`

```
Error: Invalid type specification

  on .\windows.pkr.json line 479, in variable.tenant_id[0]:
 479:                 "type": "${string}"

A type specification is either a primitive type keyword (bool, number, string)
or a complex type constructor call, like list(string).
```

Changing it to simply `"type": "string"` fixes this and validates successfully. However, this is a problem for every type including map(string), bool, list(string), and the list goes on. It appears to always be wrapping the original type specified in the HCL as `${value}`

**Comment by MertSenel** [comment]
hi @GitYukari, thanks for raising this issue. this looks a defect with the hcl2json tool itself rather than the powershell module, I've tested locally with below hcl file 

so imagine below content for `test.hcl` file

```
variable "tenant_id" {
  type    = string
  default = "${env("ARM_TENANT_ID")}"
}

variable "agent_count" {
  description = "Number of agents to create"
  default = 1
  type = number
}
```

after directly passing content into the CLI tool via command 
`get-content .\test.hcl | .\hcl2json_windows_amd64.exe` 

I'm getting result below:

```
{
    "variable": {
        "agent_count": [
            {
                "default": 1,
                "description": "Number of agents to create",
                "type": "${number}"
            }
        ],
        "tenant_id": [
            {
                "default": "${env(\"ARM_TENANT_ID\")}",
                "type": "${string}"
            }
        ]
    }
}
```

and it seems to be happening for all variable definitions with type defined explicitly. 

I don't know if this is desired behavior by design or a defect in the hcl2json tool but regardless the output is defined by the tool itself, so I recommend raising this issue in the tool's repository to the owner: 
https://github.com/tmccombs/hcl2json/issues

I keep the module up to date with the cli tool releases to if a new release fixes/changes (because I don't know if this is not the desired behavior) this behavior in the tool, the module will also reflect that change with a new version. 

Thanks
